name: first
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: morning
        run: echo "Guten Morgen"
      - name: evening
        run: echo "Guten Abend"
